# Generated by Django 5.0.6 on 2024-06-10 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='card_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cvv',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(100), django.core.validators.MaxLengthValidator(999)]),
        ),
    ]
