# Generated by Django 5.0.6 on 2024-06-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_address_address_address_city_address_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.TextField(default='text address'),
            preserve_default=False,
        ),
    ]
