# Generated by Django 5.0.6 on 2024-06-14 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address',
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='cvv',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)]),
        ),
    ]
